#!/bin/bash
# Written by Steven Shiau <steven _at_ nchc org tw> to use in DRBL 
# German translation by Michael Vinzenz <michael.vinzenz _at_ scalaris com>
# License: GPL
# Merged some of those revised by Dylan Pack <sarpulhu _at_ gmail com> on 26/Feb/2009.

#-----------------------------------------
msg_send_dhcp_request_from="Sende DHCP-Broadcast vom Gerät"
msg_failed="Abgebrochen"
msg_press_enter_to_exit='Beenden mit "Enter"...'
msg_enter_IP_add_for_this_nic="Geben Sie die IP-Adresse ein für "
msg_enter_netmask_for_this_nic="Geben Sie die Netzwerk-Maske ein für "
msg_enter_default_gateway="Geben Sie das Standard-Gateway an"
msg_enter_dns_server="Geben Sie den/die Nameserver an"
msg_put_dnsserver_to_resolv_conf="Konfiguriere Nameserver in /etc/resolv.conf als:"
msg_append_dnsserver_to_resolv_conf="Füge Nameserver in /etc/resolv.conf hinzu:"
msg_no_nic_is_found="Keine unterstützten Netzwerk-Karten gefunden."
msg_link_detected='Link vorhanden'
msg_choose_nic="Welches Netzwerkgerät wollen Sie konfigurieren"
msg_Network_config="Netzwerk-Konfiguration"
msg_choose_mode_to_setup_net="Geben Sie an, wie Sie das Netzwerk für diese Karte konfigurieren wollen"
msg_use_dhcp_broadcast="DHCP-Broadcast verwenden"
msg_use_static_ip="Statische IP-Adresse verwenden"
msg_use_pppoe_conf="PPPoE verwenden"
msg_enter_cml='Befehlszeilen-Prompt'
msg_do_it_manually='Keines davon, Sie machen es selbst.'
msg_enter_another_shell_hint_wo_netcfg_prompt='Eine neue Shell starten. Wenn Sie fertig sind, geben Sie "exit" ein, um wieder hierher zurückzukehren.'
msg_press_enter_to_continue='Weiter mit "Enter"...'
