#!/bin/bash
# Written by Steven Shiau <steven _at_ nchc org tw> to use in DRBL 
# License: GPL

#-----------------------------------------
msg_send_dhcp_request_from="Sending DHCP broadcast from device"
msg_failed="Failed"
msg_press_enter_to_exit='Press "Enter" to exit...'
msg_enter_IP_add_for_this_nic="Please enter IP Address for "
msg_enter_netmask_for_this_nic="Please enter Network Mask for "
msg_enter_default_gateway="Please enter Default Gateway"
msg_enter_dns_server="Please enter Nameserver(s)"
msg_put_dnsserver_to_resolv_conf="Setting Nameserver in /etc/resolv.conf to"
msg_append_dnsserver_to_resolv_conf="Adding Nameserver to /etc/resolv.conf:"
msg_no_nic_is_found="No supported network cards found."
msg_link_detected='Link detected'
msg_choose_nic="Which network device you want to configure"
msg_Network_config="Network Config"
msg_choose_mode_to_setup_net="Choose the mode to setup the network for this network card"
msg_use_dhcp_broadcast="Use DHCP broadcast"
msg_use_static_ip="Use static IP address"
msg_use_pppoe_conf="Use PPPoE"
msg_enter_cml='Enter command line prompt'
msg_do_it_manually='Do it manually'
msg_enter_another_shell_hint_wo_netcfg_prompt='Enter another shell. When everything is done, run "exit" to go back to the original program.'
msg_press_enter_to_continue='Press "Enter" to continue...'
