#!/bin/bash
# Written by Steven Shiau <steven _at_ nchc org tw> to use in DRBL and
# translated by Juan Ramón Martínez <jrmc77 _at_ terra es>.
# Translated and revised Alex Ibáñez López <alex.ibanez _at_ gmail com> on Mar/25/2009
# License: GPL

#-----------------------------------------
msg_send_dhcp_request_from="Enviando transmisión DHCP del dispositivo"
msg_failed="Fallo"
msg_press_enter_to_exit='Pulse "Intro" para salir...'
msg_enter_IP_add_for_this_nic="Por favor introduzca la Dirección IP para "
msg_enter_netmask_for_this_nic="Por favor introduzca la Máscara de RED para "
msg_enter_default_gateway="Por favor introduzca Gateway Por Defecto"
msg_enter_dns_server="Por favor introduzca Nameserver(s)"
msg_put_dnsserver_to_resolv_conf="Configurando Nameserver en /etc/resolv.conf a"
msg_append_dnsserver_to_resolv_conf="Añadiendo Nameserver a /etc/resolv.conf:"
msg_no_nic_is_found="No se han encontrado tarjetas de red soportadas."
msg_link_detected='Enlace_detectado'
msg_choose_nic="Que dispositivo de red desea configurar"
msg_Network_config="Configuración de Red"
msg_choose_mode_to_setup_net="Elija el modo de configurar la red para esta tarjeta de red"
msg_use_dhcp_broadcast="Usar transmisión DHCP"
msg_use_static_ip="Usar dirección IP estática"
msg_use_pppoe_conf="Usar PPPoE"
msg_enter_cml='Introduzca linea de comandos del prompt'
msg_do_it_manually='Hacerlo manualmente'
msg_enter_another_shell_hint_wo_netcfg_prompt='Introducir otro shell. Cuando acabe escriba "exit" para volver al programa original.'
msg_press_enter_to_continue='Pulse "Intro" para continuar...'
