#!/bin/bash
# Much of the translation was done by Jean-Francois Nifenecker <jean-francois.nifenecker _at_ laposte net>, 1st received on 2008/May/03, 2nd revised received on 2008/May/16, and ...
# Language files fr_FR was updated on Jul/05/2010. Thanks to Jean Francois Martinez <jfm512 _at_ free fr>
#

#-----------------------------------------
msg_send_dhcp_request_from="Envoi d'un message de diffusion DHCP à partir du périphérique"  # To be confirmed.
msg_failed="Echec"
msg_press_enter_to_exit='Appuyez sur "Entrée" pour sortir...'
msg_enter_IP_add_for_this_nic="Entrez l'adresse IP de "
msg_enter_netmask_for_this_nic="Entrez le masque réseau de "
msg_enter_default_gateway="Entrez la passerelle par défaut"
msg_enter_dns_server="Entrez le(s) serveur(s) de noms"
msg_put_dnsserver_to_resolv_conf="Paramétrage du serveur de noms dans /etc/resolv.conf pour"
msg_append_dnsserver_to_resolv_conf="Ajout du serveur de noms dans /etc/resolv.conf :"
msg_no_nic_is_found="Des cartes réseau non supportées ont été trouvées."
msg_link_detected='Liaison_détectée'
msg_choose_nic="Quel périphérique réseau voulez-vous configurer"
msg_Network_config="Configuration réseau"
msg_choose_mode_to_setup_net="Mode de configuration réseau pour la carte "
msg_use_dhcp_broadcast="Utiliser une adresse dynamique (DHCP)"
msg_use_static_ip="Utiliser une adresse IP statique"
msg_use_pppoe_conf="Utiliser PPPoE"
msg_enter_cml='Passer en ligne de commande'
msg_do_it_manually='Montage manuel'
msg_enter_another_shell_hint_wo_netcfg_prompt='Entrer dans un nouveau shell. Quand vous aurez terminé, tapez "exit" pour revenir au programme originel.'
msg_press_enter_to_continue='Appuyez sur "Entrée" pour continuer...'
