#!/bin/bash
# Written by Steven Shiau <steven _at_ nchc org tw> to use in DRBL and translated by Gianfranco Gentili <gf.gentili _at_ libero it>.
# License: GPL


#-----------------------------------------
msg_send_dhcp_request_from="Invio la trasmissione di DHCP dal dispositivo"
msg_failed="Fallito"
msg_press_enter_to_exit='Premete "Invio" per uscire ...'
msg_enter_IP_add_for_this_nic="Inserite l'indirizzo IP per "
msg_enter_netmask_for_this_nic="Inserite la Network Mask for "
msg_enter_default_gateway="Inserite il Gateway di default"
msg_enter_dns_server="Inserite i Nameserver(s)"
msg_put_dnsserver_to_resolv_conf="Impostare il Nameserver in /etc/resolv.conf a"
msg_append_dnsserver_to_resolv_conf="Aggiunta di Nameserver in /etc/resolv.conf:"
msg_no_nic_is_found="Non ho trovato nessuna scheda di rete supportata."
msg_link_detected='Link_detected'
msg_choose_nic="Quale dispositivo di rete volete configurare"
msg_Network_config="Configurazione della rete"
msg_choose_mode_to_setup_net="Scegliete il modo di impostare la rete per questa scheda di rete"
msg_use_dhcp_broadcast="Uso il DHCP broadcast"
msg_use_static_ip="Uso l'indirizzo statico IP"
msg_use_pppoe_conf="Uso PPPoE"
msg_enter_cml='Apre il prompt a riga di comando'
msg_do_it_manually='Lo dovete fare a mano'
msg_enter_another_shell_hint_wo_netcfg_prompt='Apre un'\''altra shell. Quando avete finito, digitate "exit" per tornare al programma originale.'
msg_press_enter_to_continue='Premete "Invio" per continuare ...'
