#!/bin/bash
# Written by Steven Shiau <steven _at_ nchc org tw> to use in DRBL 
# License: GPL

#-----------------------------------------
msg_send_dhcp_request_from="Włącz tryb adresu rozgłoszeniowego DHCP z urządzenia"
msg_failed="Nie powiodło się"
msg_press_enter_to_exit='Naciśnij "Enter", aby wyjść ...'
msg_enter_IP_add_for_this_nic="Wprowadź adres IP dla "
msg_enter_netmask_for_this_nic="Wprowadź maskę podsieci dla "
msg_enter_default_gateway="Wprowadź domyślną bramę"
msg_enter_dns_server="Proszę podać serwer(y) nazw "
msg_put_dnsserver_to_resolv_conf="Ustawianie serwera nazw w /etc/resolv.conf dla"
msg_append_dnsserver_to_resolv_conf="Dodanie serwera nazw do /etc/resolv.conf:"
msg_no_nic_is_found="Nie znaleziono obsługiwanych kart sieciowych."
msg_link_detected='Wykryto połączenie'
msg_choose_nic="Jakie urządzenie sieciowe chcesz skonfigurować"
msg_Network_config="Konfiguracja sieci"
msg_choose_mode_to_setup_net="Wybierz tryb, aby skonfigurować sieć dla tej karty sieciowej"
msg_use_dhcp_broadcast="Użyj transmisji DHCP"
msg_use_static_ip="Użyj statycznego adresu IP"
msg_use_pppoe_conf="Użyj PPPoE"
msg_enter_cml='Przejdź do linii poleceń/shell'
msg_do_it_manually='Zrób to ręcznie'
msg_enter_another_shell_hint_wo_netcfg_prompt='Wprowadź kolejną powłokę/shell. Kiedy wszystko zostanie zrobione, wpisz "exit", aby powrócić do oryginalnego programu.'
msg_press_enter_to_continue='Naciśnij "Enter", aby kontynuować ...'
