#!/bin/bash
# Written by Steven Shiau <steven _at_ nchc org tw> to use in DRBL and
# Translated by Marcos Pereira da Silva Cruz <marcospcruz _at_ gmail com>
# License: GPL

#-----------------------------------------
msg_send_dhcp_request_from="Enviando transmissão DHCP do dispositivo"
msg_failed="Falha"
msg_press_enter_to_exit='Pressione "Enter" para sair...'
msg_enter_IP_add_for_this_nic="Por favor introduza o Endereço IP para "
msg_enter_netmask_for_this_nic="Por favor introduza a Máscara de REDE para "
msg_enter_default_gateway="Por favor introduza Gateway Padrão"
msg_enter_dns_server="Por favor introduza Nameserver(s)"
msg_put_dnsserver_to_resolv_conf="Configurando Nameserver em /etc/resolv.conf para"
msg_append_dnsserver_to_resolv_conf="Adicionando Nameserver em /etc/resolv.conf:"
msg_no_nic_is_found="Não foram encontradas placas de rede suportadas."
msg_link_detected='Link detectado'
msg_choose_nic="Que dispositivo de rede deseja configurar"
msg_Network_config="Configuração de Rede"
msg_choose_mode_to_setup_net="Escolha o modo de configuração de rede para esta placa de rede"
msg_use_dhcp_broadcast="Usar transmissão DHCP"
msg_use_static_ip="Usar endereço IP estático"
msg_use_pppoe_conf="Usar PPPoE"
msg_enter_cml='Entre na linha de comandos do prompt'
msg_do_it_manually='Fazê-lo manualmente'
msg_enter_another_shell_hint_wo_netcfg_prompt='Entrar em outro shell. Quando acabar escreva "exit" para voltar ao programa original.'
msg_press_enter_to_continue='Pressione "Enter" para continuar...'
