#!/bin/bash
# Author: Steven Shiau <steven _at_ nchc org tw>
# License: GPL

### BEGIN INIT INFO
# Provides:          start-ocs-live
# Required-Start:    $local_fs $all
# Required-Stop:
# X-Start-Before:    
# Default-Start:     2
# Default-Stop:
### END INIT INFO

# To avoid there is no input output in rc running, we add this one:
exec </dev/console >/dev/console 2>&1

[ ! -d "/etc/ocs/ocs-live.d/" ] && exit 1
for script in /etc/ocs/ocs-live.d/S[0-9][0-9]*; do
  $script
done
