#!/bin/bash
# Author: Steven Shiau <steven _at_ nchc org tw>
# License: GPL

### BEGIN INIT INFO
# Provides:          start-drbl-live
# Required-Start:    $local_fs dbus
# Required-Stop:
# X-Start-Before:    kdm gdm3 xdm lightdm
# X-Stop-After:      kdm gdm3 xdm lightdm
# Default-Start:     2
# Default-Stop:
### END INIT INFO

# To avoid there is no input output in rc running, we add this one:
exec </dev/console >/dev/console 2>&1

[ ! -d "/etc/drbl/drbl-live.d/" ] && exit 1
for script in /etc/drbl/drbl-live.d/S[0-9][0-9]*; do
  $script
done
