#!/bin/bash
# Author: Steven Shiau <steven _at_ nchc org tw>
# License: GPL

### BEGIN INIT INFO
# Provides:          stop-drbl-live
# Required-Start:    $local_fs dbus
# Required-Stop:
# X-Start-Before:    
# X-Stop-After:      
# Default-Start:     
# Default-Stop:      0 6
### END INIT INFO

# To avoid there is no input output in rc running, we add this one:
exec </dev/console >/dev/console 2>&1

[ ! -d "/etc/drbl/drbl-live.d/" ] && exit 1
[ -z "$(ls /etc/drbl/drbl-live.d/K[0-9][0-9]* 2>/dev/null)" ] && exit 1
for script in /etc/drbl/drbl-live.d/K[0-9][0-9]*; do
  $script
done
