#!/bin/bash
# Program to change console font size
# Load gparted live functions
. /usr/share/gparted/bin/gl-functions

[ -e /etc/gparted-live/gparted-live.conf ] && . /etc/gparted-live/gparted-live.conf

# live_console_font_size
if [ -z "$live_console_font_size" ]; then
  exit 2
fi
gparted-console-font-size $live_console_font_size
