#!/bin/bash


set -e

#test_clonezilla_ocs_sr_smoke_test(){
#  echo "ocs-sr"
#  ocs-sr --help
#  retur 0
#}
#
#test_clonezilla_ocs_onthefly_smoke_test(){
#  echo "ocs-onthefly"
#  ocs-onthefly --help
#  retur 0
#}

test_ocs_blk_info(){
  echo "ocs blk info test"
  /usr/bin/ocs-blk-dev-info testOutputFile
}

test_ocs_scan_disk(){
  echo "ocs scan disk test"
  /usr/bin/ocs-scan-disk
}

#test_ocs_console_font_size(){
#  echo "ocs console font size test"
#  /usr/sbin/ocs-console-font-size
#}

test_basic_function(){
  echo "basic function test"
  # Load DRBL setting and functions
  DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"
  . $DRBL_SCRIPT_PATH/sbin/drbl-conf-functions
  . /etc/drbl/drbl-ocs.conf
  . $DRBL_SCRIPT_PATH/sbin/ocs-functions
  gen_proc_partitions_map_file
  disk_proc="$(get_disk_list $partition_table)"
}

. shunit2

