#!/bin/bash
# Author: Steven Shiau <steven _at_ nchc org tw>
# License: GPL
# Description: Program to start restoring image in Clonezilla live.
# //NOTE// We can not just run "LC_ALL=$ocs_lang ocs-sr $ocs_live_extra_param" if the embedded image is on the recovery iso, since without ocs-live-env-prepare, it won't show in $ocsroot. That's why we have this program.

# Load DRBL setting and functions
DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"

. $DRBL_SCRIPT_PATH/sbin/drbl-conf-functions
. /etc/drbl/drbl-ocs.conf
. $DRBL_SCRIPT_PATH/sbin/ocs-functions

# load the setting for clonezilla live.
[ -e /etc/ocs/ocs-live.conf ] && . /etc/ocs/ocs-live.conf

# Functions
USAGE() {
    echo "$ocs - Program to start restoring image in Clonezilla live"
    echo "Usage:"
    echo "To run $ocs:"
    echo "$ocs"
    echo "Ex:"
    echo "To start restoring image in Clonezilla live, run"
    echo "   $ocs"
    echo "If what you want is just saving, use \"ocs-live-save\" instead of this program."
    echo "If what you want is for both saving and restoring, use \"ocs-live-general\" instead of this program."
    echo "///NOTE/// Use this program carefully!!! It might overwrite all the data on your hard drive!!!"
} # end of USAGE

####################
### Main program ###
####################

ocs=`basename $0`
#
check_if_root
#
while [ $# -gt 0 ]; do
 case "$1" in
   -*)     echo "${0}: ${1}: invalid option" >&2
           USAGE >& 2
           exit 2 ;;
   *)      break ;;
 esac
done

# Get the live media mount point.
get_live_media_mnt_point

# prepare the clonezilla live environment.
ocs-live-env-prepare

# ocs_lang and ocs_live_extra_param are loaded from /etc/ocs/ocs-live.conf
LC_ALL=$ocs_lang ocs-sr $ocs_live_extra_param
rc=$?
if [ "$rc" -gt 0 ]; then
  # If something goes wrong, pause here otherwise if it's in batch mode
  #(like recovery iso created by recovery-iso-zip), the TUI (poweroff/reboot/cmd)
  # in function run_post_cmd_when_clone_end will override the error messages.
  echo -n "Press enter to continue..."
  read
fi
