#!/bin/bash
# Author: Steven Shiau <steven _at_ nchc org tw>
# License: GPL
# Description: Program to start saving image in Clonezilla live.

# We need to know ocsroot and functions in ocs-functions and some variables from drbl-ocs.conf.
DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"

. $DRBL_SCRIPT_PATH/sbin/drbl-conf-functions
. /etc/drbl/drbl-ocs.conf
. $DRBL_SCRIPT_PATH/sbin/ocs-functions

# Functions
USAGE() {
    echo "$ocs - Program to start saving image in Clonezilla live"
    echo "Usage:"
    echo "To run $ocs:"
    echo "$ocs"
    echo "Ex:"
    echo "To start saving image in Clonezilla live, run"
    echo "   $ocs"
    echo "If what you want is just restoring, use \"ocs-live-restore\" instead of this program."
    echo "If what you want is for both saving and restoring, use \"ocs-live-general\" instead of this program."
    echo "///NOTE/// Use this program carefully!!! It might overwrite all the data on your hard drive!!!"
} # end of USAGE

####################
### Main program ###
####################

ocs=`basename $0`
#
check_if_root
#
while [ $# -gt 0 ]; do
 case "$1" in
   -*)     echo "${0}: ${1}: invalid option" >&2
           USAGE >& 2
           exit 2 ;;
   *)      break ;;
 esac
done

# Clean /etc/motd to avoid the following message is missing.
echo -n "" > /etc/motd

# Get the live media mount point.
get_live_media_mnt_point

# Prepare default ocsroot.
if mkdir -p /$LIVE_MEDIA/$ocsroot 2>/dev/null; then
  mkdir -p `dirname $ocsroot`
  ln -fs /$LIVE_MEDIA/$ocsroot $ocsroot
else
  # mkdir a mount point to be used later.
  mkdir -p $ocsroot
fi
ask_language_if_supported_with_bterm
[ -z "$ocs_lang" ] && ocs_lang=en
ask_and_load_lang_set $ocs_lang

# run the main program
check_if_tty1_and_continue

# Do not ask powerer/reboot/choose (-p) in ocs-sr,  just use "-p true". Since it might be in bterm, and Debian live "Press Enter" message when poweroff/shutdown might be coverd by bterm and user will not have any idea what's happening after choose poweroff/reboot.
ocs-live -p true
# Show prompt
show-general-ocs-live-prompt
