#!/bin/bash
# Author: Steven Shiau <steven _at_ nchc org tw>
# License: GPL

# Load DRBL setting and functions
DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/opt/drbl/}"

. $DRBL_SCRIPT_PATH/sbin/drbl-conf-functions
. $DRBL_SCRIPT_PATH/conf/drbl-ocs.conf
. $DRBL_SCRIPT_PATH/sbin/ocs-functions

# 
prog="$(basename $0)"
USAGE() {
    echo "Usage:"
    echo "To see the clonezilla live help message:"
    echo "$prog" 
}
type=$1

ask_language_if_supported_with_bterm
[ -z "$ocs_lang" ] && ocs_lang=en
ask_and_load_lang_set $ocs_lang

show-general-ocs-live-prompt
