#!/bin/bash
# Program to change console font size
# Load DRBL setting and functions
DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"
. $DRBL_SCRIPT_PATH/sbin/drbl-conf-functions
. /etc/drbl/drbl-ocs.conf
. $DRBL_SCRIPT_PATH/sbin/ocs-functions
. /etc/ocs/ocs-live.conf

# live_console_font_size
if [ -z "$live_console_font_size" ]; then
  exit 2
fi
ocs-console-font-size $live_console_font_size
