#!/bin/bash

# Load DRBL setting and functions
DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"
. $DRBL_SCRIPT_PATH/sbin/drbl-conf-functions
. /etc/drbl/drbl-ocs.conf
. $DRBL_SCRIPT_PATH/sbin/ocs-functions

#
if [ -x "$DRBL_SCRIPT_PATH/setup/files/misc/arm-wol" ]; then
  $DRBL_SCRIPT_PATH/setup/files/misc/arm-wol
fi
