#!/bin/bash
# Touch a file to indicate that the jobs in ocs-live.d have been finished.
mkdir -p /var/lib/live/clonezilla
touch /var/lib/live/clonezilla/ocs-live.d
echo "Finished Clonezilla live env preparing..."
