#!/bin/bash
# Author: Steven Shiau <steven _at_ nchc org tw>
# License: GPL

# The working dir for the binary hook is the binary/ under working dir (e.g. debian-live/binary/), not in the chroot.
# Put grub2 efi boot loader
# The name server is deconfigured, we have to enable it so the apt-get will work in ocs-gen-grub2-efi-bldr.

# Part I: EFI-related files
cp -a /etc/resolv.conf ../chroot/etc/resolv.conf
chroot ../chroot mkdir -p /EFI/boot
chroot ../chroot /bin/bash gl-gen-grub2-efi-bldr /EFI/boot
rm -rf EFI
mv ../chroot/EFI ./
# After this, the chroot/etc/resolv.conf should not be deconfigured, we still need to keep it. Since after this binary hook, the live-build still need to use apt-get to download genisoimage and syslinux.
# echo -n "" > chroot/etc/resolv.conf

# Part II: misc
# Clean the duplicated vmlinuz-* and initrd-*, we just want vmlinuz and initrd so that the iso file can be smaller.
rm -f live/vmlinuz-* live/initrd.img-*

### THE END ###
# DO NOT PUT ANY SCRIPT AFTHER THIS!!!
rm -rf live-binary-hook-dir/
