#!/bin/sh
# Load functions
. /usr/share/gparted/bin/gl-functions

get_gui_dialog

$DIALOG	--title "EXIT" \
        --icon /usr/share/pixmaps/gparted-live/shutdown-menu.xpm \
        --radiolist "" 16 30 0 \
        "Reboot"  "" ON \
        "Shutdown"  "" off \
        "Logout"  "" off 2>/tmp/checklist.tmp.$$

retval=$?
choice=`cat /tmp/checklist.tmp.$$`
rm -f /tmp/checklist.tmp.$$

case $choice in
	"Reboot")
		reboot
		;;
	"Shutdown")
		halt -p
		;;	
	"Logout")
		gl-killx
		;;
esac
