#!/bin/bash

choice="$(zenity --list --text "Exit" --radiolist  --column "Pick" --column "Opinion" TRUE Reboot FALSE Shutdown FALSE Logout)";

case $choice in
	"Reboot")
		reboot
		;;
	"Shutdown")
		halt -p
		;;	
	"Logout")
		gl-killx
		;;
esac
